export interface Pokemon {
  key: string;
  abilities: string;
  against_bug: string;
  against_dark: string;
  against_dragon: string;
  against_electric: string;
  against_fairy: string;
  against_fight: string;
  against_fire: string;
  against_flying: string;
  against_ghost: string;
  against_grass: string;
  against_ground: string;
  against_ice: string;
  against_normal: string;
  against_poison: string;
  against_psychic: string;
  against_rock: string;
  against_steel: string;
  against_water: string;
  attack: string;
  base_egg_steps: string;
  base_happiness: string;
  base_total: string;
  capture_rate: string;
  classfication: string;
  defense: string;
  experience_growth: string;
  height_m: string;
  hp: string;
  japanese_name: string;
  name: string;
  percentage_male: string;
  pokedex_number: string;
  sp_attack: string;
  sp_defense: string;
  speed: string;
  type1: PokemonType;
  type2: PokemonType;
  weight_kg: string;
  generation: string;
  is_legendary: string;
}

export type PokemonType =
  | 'grass'
  | 'fire'
  | 'water'
  | 'bug'
  | 'normal'
  | 'poison'
  | 'electric'
  | 'ground'
  | 'fairy'
  | 'fighting'
  | 'psychic'
  | 'rock'
  | 'ghost'
  | 'ice'
  | 'dragon'
  | 'dark'
  | 'steel'
  | 'flying';
